### ISSUE TITLE
Tracking issue: Clearer, more effective error messages

### ISSUE THREAD

**Issue by obi1kenobi** [obi1kenobi/trustfall#92]
We should aim to always be improving the quality of our error messages.

 Here are outstanding issues with them:
- [ ] Errors don't currently include span information. This is a big lift and will require plumbing that information throughout the frontend.
- [ ] When a query fails to validate against the schema, `.unwrap()` on the `Result` produces a `Debug`-style printout like `CompilationError(ValidationError(NonExistentPath(["CrateDiff", "baseline", "item", "Enum", "variant", "StructVariant", "field"])))`. This is not ideal:
  - [ ] it should clearly mention the problem is that the query didn't match the schema
  - [ ] it should ideally include `Display` output rather than `Debug` output
  - [ ] perhaps the naming can be better as well?
